import Head from "next/head";
import {
  Heading,
  Box,
  Flex,
  Grid,
  GridItem,
  Image,
  Text,
  Divider,
  Icon,
  Input,
  Link,
  Button,
  InputGroup,
  InputLeftElement,
} from "@chakra-ui/react";
import { HiMenu } from "react-icons/hi";
import { FaSearch } from "react-icons/fa";
import Header from "../components/header";
import Hero from "../components/hero";
import BlogList from "@/components/blog/BlogList";
import Footer from "@/components/footer";
import MainLayout from "@/layouts/MainLayout";

const blogs = [
  {
    id: 1,
    title:
      "I had not achieved anything in my life until I understood this one thing",
    post_date: "Oct 21, 2022",
    body: "I'm baby church-key cardigan Brooklyn yes plz forage quinoa cornhole meggings ",
    author: "syaifulhusein",
    banner_image:
      "https://images.pexels.com/photos/837358/pexels-photo-837358.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
  },
  {
    id: 2,
    title: "Don’t look at someone else’s watch",
    post_date: "Sep 11, 2022",
    body: "JOMO vape bruh vegan, iceland echo park cray craft beer hashtag selfies seitan jean shorts tofu. Chia enamel pin af, listicle celiac semiotics crucifix plaid farm-to-table pug readymade. Offal poke lo-fi truffaut. Tousled glossier post-ironic enamel pin, schlitz raw denim scenester neutra raclette austin DSA la croix selfies. 3 wolf moon affogato beard organic hexagon synth. Meditation cray raw denim man braid chicharrones offal next level hot chicken forage skateboard kombucha. Forage selvage drinking vinegar pork belly schlitz. Lomo bicycle rights XOXO organic trust fund green juice adaptogen try-hard cronut asymmetrical. Yes plz sustainable salvia enamel pin, chambray ramps narwhal.",
    author: "syaifulhusein",
    banner_image:
      "https://images.pexels.com/photos/39866/entrepreneur-startup-start-up-man-39866.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
  },
  {
    id: 3,
    title: "Only in this way will you achieve everything you want",
    post_date: "Jan 20, 2022",
    body: "Brooklyn fixie authentic taxidermy +1 put a bird on it coloring book bruh YOLO williamsburg skateboard hell of freegan keytar. Seitan chambray single-origin coffee, shabby chic hell of everyday carry bushwick shoreditch 90's hot chicken mukbang. Chia air plant shoreditch activated charcoal cardigan hella. Banjo meggings tote bag sartorial. Whatever bespoke enamel pin actually, coloring book shoreditch pug. Big mood viral narwhal, fixie seitan craft beer lo-fi humblebrag yr hammock microdosing cliche waistcoat small batch sus. Thundercats sustainable narwhal, vice fanny pack knausgaard sus raw denim small batch freegan asymmetrical wolf salvia. Same tumeric JOMO bespoke 90's. Lo-fi subway tile roof party, mustache put a bird on it quinoa offal.",
    author: "syaifulhusein",
    banner_image:
      "https://images.pexels.com/photos/1709003/pexels-photo-1709003.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
  },
  {
    id: 4,
    title: "Node.js from scratch!",
    post_date: "Jan 20, 2022",
    body: "Brooklyn fixie authentic taxidermy +1",
    author: "syaifulhusein",
    banner_image:
      "https://images.pexels.com/photos/15113597/pexels-photo-15113597.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <Header />
        <Box as="main">
          <Hero />
          <BlogList blogs={blogs} />
        </Box>
      </MainLayout>
    </>
  );
}
